-- ============================================================
-- TORQUED — Migration 024: ef_parts_data (engine-family-keyed pricing)
-- Each row = one job's price range for one engine family.
-- category_id looked up by slug so serial IDs don't need to be hardcoded.
-- ============================================================

CREATE TABLE IF NOT EXISTS ef_parts_data (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    engine_family_id   text NOT NULL REFERENCES engine_families(family_id),
    category_id        integer NOT NULL REFERENCES part_categories(id),
    total_job_low      integer NOT NULL,   -- NZD GST-inclusive
    total_job_high     integer NOT NULL,
    hours_low          numeric,
    hours_high         numeric,
    source_anchor      text,
    confidence         integer DEFAULT 2,
    notes              text,
    price_updated_at   timestamptz DEFAULT now(),
    UNIQUE(engine_family_id, category_id)
);

CREATE INDEX IF NOT EXISTS idx_ef_parts_family ON ef_parts_data(engine_family_id);
CREATE INDEX IF NOT EXISTS idx_ef_parts_category ON ef_parts_data(category_id);

-- RLS
ALTER TABLE ef_parts_data ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "ef_parts_data_public_read" ON ef_parts_data;
CREATE POLICY "ef_parts_data_public_read" ON ef_parts_data FOR SELECT USING (true);

-- ── Seed ef_parts_data ────────────────────────────────────────────────────────
-- Uses subquery to resolve category slug → id, so no hardcoded serial IDs.

INSERT INTO ef_parts_data (
    engine_family_id, category_id,
    total_job_low, total_job_high, hours_low, hours_high,
    source_anchor, confidence, notes
)
SELECT v.* FROM (VALUES
  ('TOY_1NZFE_15', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 150, 250, 0.5, 0.8, 'brake_pads_economy', 3, 'Per axle, economy tier'),
  ('TOY_1NZFE_15', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 150, 250, 0.5, 0.8, 'brake_pads_economy', 3, NULL),
  ('TOY_1NZFE_15', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 150, 230, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('TOY_1NZFE_15', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 280, 380, 1.2, 1.8, 'comprehensive_service_economy', 3, NULL),
  ('TOY_2NZFE_13', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 150, 230, 0.5, 0.8, 'brake_pads_economy', 3, NULL),
  ('TOY_2NZFE_13', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 150, 230, 0.5, 0.8, 'brake_pads_economy', 3, NULL),
  ('TOY_2NZFE_13', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 150, 220, 0.5, 1.0, 'basic_service_economy', 3, 'Toyota official menu: Yaris 3-cyl $170 (this engine is 4-cyl, similar pricing)'),
  ('TOY_1KRFE_10', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 150, 220, 0.4, 0.7, 'brake_pads_economy', 3, NULL),
  ('TOY_1KRFE_10', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 150, 210, 0.5, 0.9, 'basic_service_economy', 3, 'Toyota official menu: Yaris 3-cyl $170'),
  ('TOY_2ZRFE_18', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 180, 280, 0.5, 0.8, 'brake_pads_economy', 3, NULL),
  ('TOY_2ZRFE_18', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 180, 280, 0.5, 0.8, 'brake_pads_economy', 3, NULL),
  ('TOY_2ZRFE_18', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 170, 240, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('TOY_2ZRFE_18', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 290, 380, 1.2, 1.8, 'comprehensive_service_economy', 3, 'My Auto Shop NZ: Corolla comprehensive avg $326'),
  ('TOY_2ZRFXE_18_HYBRID', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 200, 320, 0.5, 0.9, 'brake_pads_mid', 3, 'Regen braking — pads last longer but cost slightly more'),
  ('TOY_2ZRFXE_18_HYBRID', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 200, 320, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('TOY_2ZRFXE_18_HYBRID', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 180, 260, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('TOY_2ZRFXE_18_HYBRID', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 320, 420, 1.4, 2.0, 'comprehensive_service_mid', 3, NULL),
  ('TOY_2ZRFXE_18_HYBRID', (SELECT id FROM part_categories WHERE slug = 'hv_battery_refurb'), 1500, 2000, 2.5, 4.0, 'hv_battery_aqua_prius_g23_refurb', 3, 'Prius gen3 fits in refurb tier; gen4 uses larger pack — see TOY_2ZRFXE_18_HYBRID_G4'),
  ('TOY_2ZRFXE_18_HYBRID', (SELECT id FROM part_categories WHERE slug = 'hv_battery_new_genuine'), 2000, 4000, 2.5, 4.0, 'hv_battery_aqua_prius_g23_new', 3, NULL),
  ('TOY_1NZFXE_15_HYBRID', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 180, 280, 0.5, 0.8, 'brake_pads_mid', 3, NULL),
  ('TOY_1NZFXE_15_HYBRID', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 180, 280, 0.5, 0.8, 'brake_pads_mid', 3, NULL),
  ('TOY_1NZFXE_15_HYBRID', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 170, 240, 0.6, 1.0, 'basic_service_mid', 3, NULL),
  ('TOY_1NZFXE_15_HYBRID', (SELECT id FROM part_categories WHERE slug = 'hv_battery_refurb'), 1500, 2000, 2.5, 3.5, 'hv_battery_aqua_prius_g23_refurb', 3, NULL),
  ('TOY_1NZFXE_15_HYBRID', (SELECT id FROM part_categories WHERE slug = 'hv_battery_new_genuine'), 2000, 4000, 2.5, 3.5, 'hv_battery_aqua_prius_g23_new', 3, NULL),
  ('TOY_1ZRFE_16', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 170, 270, 0.5, 0.8, 'brake_pads_economy', 3, NULL),
  ('TOY_1ZRFE_16', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 170, 240, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('TOY_2ARFE_25', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 220, 340, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('TOY_2ARFE_25', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 220, 340, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('TOY_2ARFE_25', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 200, 290, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('TOY_2ARFE_25', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 380, 500, 1.4, 2.0, 'comprehensive_service_mid', 3, NULL),
  ('TOY_2ARFXE_25_HYBRID', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 240, 360, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('TOY_2ARFXE_25_HYBRID', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 240, 360, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('TOY_2ARFXE_25_HYBRID', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 220, 320, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('TOY_2ARFXE_25_HYBRID', (SELECT id FROM part_categories WHERE slug = 'hv_battery_refurb'), 2000, 2500, 3.0, 4.5, 'hv_battery_camry_hybrid_refurb', 3, NULL),
  ('TOY_2ARFXE_25_HYBRID', (SELECT id FROM part_categories WHERE slug = 'hv_battery_new_genuine'), 5000, 7000, 3.0, 4.5, 'hv_battery_prius_g4_camry_new', 3, NULL),
  ('TOY_A25AFXS_25_HYBRID', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 250, 380, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('TOY_A25AFXS_25_HYBRID', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 250, 380, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('TOY_A25AFXS_25_HYBRID', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 240, 340, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('TOY_A25AFXS_25_HYBRID', (SELECT id FROM part_categories WHERE slug = 'hv_battery_new_genuine'), 6000, 8000, 3.0, 4.5, 'hv_battery_rav4_hybrid_new', 3, NULL),
  ('TOY_1KDFTV_30_DIESEL', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 900, 1400, 4.0, 6.0, 'cambelt_hilux_diesel_1kd_2kd', 3, 'Includes water pump, tensioner, idler. Hilux service manual interval 150,000km'),
  ('TOY_1KDFTV_30_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 230, 360, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('TOY_1KDFTV_30_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 230, 360, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('TOY_1KDFTV_30_DIESEL', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 205, 290, 0.8, 1.2, 'basic_service_mid', 3, 'Toyota NZ official menu: Hilux 4cyl $205'),
  ('TOY_1KDFTV_30_DIESEL', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 380, 520, 1.5, 2.2, 'comprehensive_service_mid', 3, NULL),
  ('TOY_2KDFTV_25_DIESEL', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 900, 1400, 4.0, 6.0, 'cambelt_hilux_diesel_1kd_2kd', 3, NULL),
  ('TOY_2KDFTV_25_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 230, 360, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('TOY_2KDFTV_25_DIESEL', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 205, 290, 0.8, 1.2, 'basic_service_mid', 3, NULL),
  ('TOY_1GDFTV_28_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 240, 380, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('TOY_1GDFTV_28_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 240, 380, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('TOY_1GDFTV_28_DIESEL', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 220, 310, 0.8, 1.2, 'basic_service_mid', 3, 'Toyota NZ official: Hilux 4cyl $205 (1GD slightly higher due to DPF service)'),
  ('TOY_1GDFTV_28_DIESEL', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 400, 550, 1.5, 2.2, 'comprehensive_service_mid', 3, NULL),
  ('TOY_2GDFTV_24_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 230, 360, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('TOY_2GDFTV_24_DIESEL', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 220, 310, 0.8, 1.2, 'basic_service_mid', 3, NULL),
  ('TOY_1GRFE_40_V6', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 280, 420, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('TOY_1GRFE_40_V6', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 250, 360, 0.8, 1.2, 'basic_service_premium', 3, NULL),
  ('TOY_1GRFE_40_V6', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 420, 580, 1.5, 2.2, 'comprehensive_service_mid', 3, NULL),
  ('TOY_2GRFE_35_V6', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 280, 420, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('TOY_2GRFE_35_V6', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 250, 360, 0.8, 1.2, 'basic_service_premium', 3, NULL),
  ('TOY_2GRFE_35_V6', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 420, 580, 1.5, 2.2, 'comprehensive_service_mid', 3, NULL),
  ('TOY_1AZFE_20', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 180, 280, 0.5, 0.8, 'brake_pads_economy', 3, NULL),
  ('TOY_1AZFE_20', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 170, 240, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('TOY_2AZFE_24', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 200, 320, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('TOY_2AZFE_24', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 200, 290, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('VW_EA211_14_TSI', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 850, 1200, 4.0, 5.5, 'cambelt_vw_ea211', 3, 'Miles Continental VW NZ: Golf 5 from $909, Tiguan from $959. TECHNICAL BULLETIN: reinforced kevlar belt — 210,000km interval, but many workshops still default to 5yr/100k. Confirm with VIN.'),
  ('VW_EA211_14_TSI', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 280, 420, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('VW_EA211_14_TSI', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 280, 420, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('VW_EA211_14_TSI', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 280, 380, 0.8, 1.2, 'basic_service_mid', 3, NULL),
  ('VW_EA211_14_TSI', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 400, 550, 1.4, 2.0, 'comprehensive_service_mid', 3, NULL),
  ('VW_EA888_20_TSI', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 350, 500, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('VW_EA888_20_TSI', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 320, 480, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('VW_EA888_20_TSI', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 320, 420, 0.8, 1.2, 'basic_service_premium', 3, NULL),
  ('VW_EA888_20_TSI', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 500, 700, 1.5, 2.2, 'comprehensive_service_premium', 3, NULL),
  ('VW_EA189_20_TDI', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 1000, 1400, 4.5, 6.0, 'cambelt_japanese_mid', 2, 'Decomposed from Euro mid range; includes water pump'),
  ('VW_EA189_20_TDI', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 280, 420, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('VW_EA189_20_TDI', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 300, 400, 0.9, 1.3, 'basic_service_mid', 3, NULL),
  ('VW_EA189_20_TDI', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 450, 600, 1.5, 2.2, 'comprehensive_service_mid', 3, NULL),
  ('VW_EA211_GTE_PHEV', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 850, 1200, 4.0, 5.5, 'cambelt_vw_ea211', 3, NULL),
  ('VW_EA211_GTE_PHEV', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 320, 480, 0.6, 1.0, 'brake_pads_mid', 3, 'Regen braking extends pad life'),
  ('VW_EA211_GTE_PHEV', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 320, 480, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('VW_EA211_GTE_PHEV', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 320, 430, 0.8, 1.2, 'basic_service_premium', 3, NULL),
  ('VW_EA211_GTE_PHEV', (SELECT id FROM part_categories WHERE slug = 'dq400e_oil_service'), 450, 650, 1.5, 2.5, 'comprehensive_service_premium', 2, 'DQ400e wet-clutch DCT requires specific G055540 ATF + filter, every 60,000km. NZ workshops vary widely on pricing.'),
  ('NIS_HR15DE_15', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 160, 250, 0.5, 0.8, 'brake_pads_economy', 3, NULL),
  ('NIS_HR15DE_15', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 170, 240, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('NIS_MR18DE_18', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 170, 270, 0.5, 0.8, 'brake_pads_economy', 3, NULL),
  ('NIS_MR18DE_18', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 180, 250, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('NIS_MR20DE_20', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 200, 320, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('NIS_MR20DE_20', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 200, 320, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('NIS_MR20DE_20', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 200, 290, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('NIS_MR20DE_20', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 380, 500, 1.4, 2.0, 'comprehensive_service_mid', 3, NULL),
  ('NIS_QR25DE_25', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 220, 340, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('NIS_QR25DE_25', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 210, 300, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('NIS_VQ35DE_35_V6', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 320, 480, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('NIS_VQ35DE_35_V6', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 260, 360, 0.8, 1.2, 'basic_service_premium', 3, NULL),
  ('NIS_LEAF_BEV', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 200, 320, 0.5, 0.9, 'brake_pads_mid', 3, 'Regen braking means pads last very long'),
  ('NIS_LEAF_BEV', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 200, 320, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('NIS_LEAF_BEV', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 150, 220, 0.5, 0.9, 'basic_service_economy', 3, 'No engine oil. Cabin filter, brake fluid, inverter coolant check, 12V battery check.'),
  ('NIS_LEAF_BEV', (SELECT id FROM part_categories WHERE slug = 'hv_battery_used_24kwh'), 4500, 7500, 3.0, 5.0, 'hv_battery_leaf_24kwh_used', 3, 'EVs Enhanced NZ — used pack from damaged vehicle. Nissan NZ does NOT sell new packs.'),
  ('NIS_LEAF_BEV', (SELECT id FROM part_categories WHERE slug = 'hv_battery_upgrade_40kwh'), 15000, 23000, 4.0, 6.0, 'hv_battery_leaf_40kwh_upgrade', 3, 'Major capacity upgrade, not like-for-like'),
  ('MAZ_SKYACTIVG_20', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 220, 340, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('MAZ_SKYACTIVG_20', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 220, 340, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('MAZ_SKYACTIVG_20', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 200, 290, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('MAZ_SKYACTIVG_20', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 380, 500, 1.4, 2.0, 'comprehensive_service_mid', 3, NULL),
  ('MAZ_SKYACTIVG_25', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 240, 360, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('MAZ_SKYACTIVG_25', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 220, 310, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('MAZ_SKYACTIVD_22', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 250, 370, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('MAZ_SKYACTIVD_22', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 240, 330, 0.8, 1.2, 'basic_service_mid', 3, NULL),
  ('MAZ_SKYACTIVD_22', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 420, 550, 1.5, 2.2, 'comprehensive_service_mid', 3, NULL),
  ('MAZ_ZY_VE_15', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 160, 250, 0.5, 0.8, 'brake_pads_economy', 3, NULL),
  ('MAZ_ZY_VE_15', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 160, 230, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('MAZ_SKYACTIVG_15', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 170, 270, 0.5, 0.8, 'brake_pads_economy', 3, NULL),
  ('MAZ_SKYACTIVG_15', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 170, 240, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('HON_L13_L15_13_15', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 170, 270, 0.5, 0.8, 'brake_pads_economy', 3, NULL),
  ('HON_L13_L15_13_15', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 180, 250, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('HON_L15B_15T', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 220, 340, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('HON_L15B_15T', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 230, 320, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('HON_R18A_18', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 180, 280, 0.5, 0.8, 'brake_pads_economy', 3, NULL),
  ('HON_R18A_18', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 190, 260, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('HON_K20_20', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 220, 340, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('HON_K20_20', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 220, 300, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('HON_K24_24', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 230, 350, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('HON_K24_24', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 230, 350, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('HON_K24_24', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 230, 320, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('HON_LDA_IMA_HYBRID', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 200, 320, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('HON_LDA_IMA_HYBRID', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 190, 270, 0.6, 1.0, 'basic_service_mid', 3, NULL),
  ('HON_LDA_IMA_HYBRID', (SELECT id FROM part_categories WHERE slug = 'hv_battery_refurb'), 1800, 2800, 2.5, 4.0, 'hv_battery_aqua_prius_g23_refurb', 2, 'Honda IMA pack — similar tier to Aqua/Prius gen2 refurb'),
  ('HON_LEB_15_IDCD_HYBRID', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 220, 340, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('HON_LEB_15_IDCD_HYBRID', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 200, 280, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('HON_LEB_15_IDCD_HYBRID', (SELECT id FROM part_categories WHERE slug = 'hv_battery_refurb'), 2000, 3200, 2.5, 4.0, 'hv_battery_aqua_prius_g23_refurb', 2, 'i-DCD Li-ion pack — refurb tier higher than IMA NiMH'),
  ('SUB_EJ25_25_BOXER_BELT', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 800, 1200, 4.5, 6.5, 'cambelt_japanese_mid', 3, 'Boxer engine cambelt — more labour due to access. Replace water pump + tensioner at same time.'),
  ('SUB_EJ25_25_BOXER_BELT', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 220, 340, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('SUB_EJ25_25_BOXER_BELT', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 220, 340, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('SUB_EJ25_25_BOXER_BELT', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 220, 310, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('SUB_EJ25_25_BOXER_BELT', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 400, 540, 1.5, 2.2, 'comprehensive_service_mid', 3, NULL),
  ('SUB_EJ20_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 900, 1300, 4.5, 6.5, 'cambelt_japanese_mid', 3, NULL),
  ('SUB_EJ20_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 300, 450, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('SUB_EJ20_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 280, 420, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('SUB_EJ20_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 250, 360, 0.8, 1.2, 'basic_service_premium', 3, NULL),
  ('SUB_FB25_25_CHAIN', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 230, 360, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('SUB_FB25_25_CHAIN', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 230, 360, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('SUB_FB25_25_CHAIN', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 230, 320, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('SUB_FB25_25_CHAIN', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 400, 540, 1.5, 2.2, 'comprehensive_service_mid', 3, NULL),
  ('SUB_FB20_20_CHAIN', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 210, 320, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('SUB_FB20_20_CHAIN', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 220, 300, 0.7, 1.1, 'basic_service_economy', 3, NULL),
  ('FORD_P5AT_32_TDCI', (SELECT id FROM part_categories WHERE slug = 'wet_belt_replacement'), 1800, 2800, 6.0, 9.0, 'cambelt_ford_ranger_wet_belt', 3, 'Wet belt is INSIDE engine, runs in oil. NZ workshops (KAAR Auckland) doing this job regularly. Includes new belt + oil pump pickup screen where needed. Significantly more labour than dry belt.'),
  ('FORD_P5AT_32_TDCI', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 280, 420, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('FORD_P5AT_32_TDCI', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 260, 400, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('FORD_P5AT_32_TDCI', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 250, 350, 0.8, 1.2, 'basic_service_premium', 3, NULL),
  ('FORD_P5AT_32_TDCI', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 450, 600, 1.5, 2.2, 'comprehensive_service_mid', 3, NULL),
  ('FORD_P4AT_22_TDCI', (SELECT id FROM part_categories WHERE slug = 'wet_belt_replacement'), 1500, 2400, 5.5, 8.5, 'cambelt_ford_ranger_wet_belt', 2, NULL),
  ('FORD_P4AT_22_TDCI', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 260, 400, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('FORD_P4AT_22_TDCI', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 240, 340, 0.8, 1.2, 'basic_service_mid', 3, NULL),
  ('FORD_YN2S_20_BITURBO', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 300, 450, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('FORD_YN2S_20_BITURBO', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 280, 380, 0.8, 1.2, 'basic_service_premium', 3, NULL),
  ('MIT_4N15_24_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 240, 360, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('MIT_4N15_24_DIESEL', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 230, 320, 0.8, 1.2, 'basic_service_mid', 3, NULL),
  ('MIT_4B11_4B12_20_24', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 210, 320, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('MIT_4B11_4B12_20_24', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 210, 300, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('MIT_OUTLANDER_PHEV_24', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 240, 360, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('MIT_OUTLANDER_PHEV_24', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 230, 320, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('MIT_OUTLANDER_PHEV_24', (SELECT id FROM part_categories WHERE slug = 'hv_battery_refurb'), 4000, 7000, 3.5, 5.5, 'hv_battery_camry_hybrid_refurb', 2, 'Outlander PHEV HV pack 12-13.8kWh — larger than Toyota hybrids, refurb pricing extrapolated. Verify with NZ Mitsubishi specialist.'),
  ('SUZ_K12B_12', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 150, 230, 0.4, 0.7, 'brake_pads_economy', 3, NULL),
  ('SUZ_K12B_12', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 150, 220, 0.5, 0.9, 'basic_service_economy', 3, NULL),
  ('SUZ_K14_14', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 200, 310, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('SUZ_K14_14', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 190, 270, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('SUZ_M16A_16', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 170, 260, 0.5, 0.8, 'brake_pads_economy', 3, NULL),
  ('SUZ_M16A_16', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 170, 240, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('HKM_G4FC_16', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 550, 800, 3.5, 5.0, 'cambelt_japanese_economy', 3, NULL),
  ('HKM_G4FC_16', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 170, 270, 0.5, 0.8, 'brake_pads_economy', 3, NULL),
  ('HKM_G4FC_16', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 180, 250, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('HKM_G4FG_G4NA_CHAIN', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 190, 290, 0.5, 0.8, 'brake_pads_economy', 3, NULL),
  ('HKM_G4FG_G4NA_CHAIN', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 190, 290, 0.5, 0.8, 'brake_pads_economy', 3, NULL),
  ('HKM_G4FG_G4NA_CHAIN', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 190, 270, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('HKM_G4FG_G4NA_CHAIN', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 320, 430, 1.4, 2.0, 'comprehensive_service_economy', 3, NULL),
  ('HKM_D4HA_20_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 220, 340, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('HKM_D4HA_20_DIESEL', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 230, 320, 0.8, 1.2, 'basic_service_mid', 3, NULL),
  ('ISU_4JJ1_30_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 250, 380, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('ISU_4JJ1_30_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 240, 360, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('ISU_4JJ1_30_DIESEL', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 240, 330, 0.8, 1.2, 'basic_service_mid', 3, NULL),
  ('BMW_N20_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 400, 600, 0.6, 1.0, 'brake_pads_luxury', 3, NULL),
  ('BMW_N20_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 400, 600, 0.6, 1.0, 'brake_pads_luxury', 3, NULL),
  ('BMW_N20_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 380, 500, 0.9, 1.3, 'basic_service_premium', 3, NULL),
  ('BMW_N20_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 600, 850, 1.6, 2.4, 'comprehensive_service_premium', 3, NULL),
  ('BMW_B48_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 400, 600, 0.6, 1.0, 'brake_pads_luxury', 3, NULL),
  ('BMW_B48_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 400, 520, 0.9, 1.3, 'basic_service_premium', 3, NULL),
  ('BMW_B48_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 600, 850, 1.6, 2.4, 'comprehensive_service_premium', 3, NULL),
  ('BMW_B47_20_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 400, 600, 0.6, 1.0, 'brake_pads_luxury', 3, NULL),
  ('BMW_B47_20_DIESEL', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 400, 520, 0.9, 1.3, 'basic_service_premium', 3, NULL),
  ('BMW_B47_20_DIESEL', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 600, 850, 1.6, 2.4, 'comprehensive_service_premium', 3, NULL),
  ('MB_M274_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 420, 600, 0.6, 1.0, 'brake_pads_luxury', 3, NULL),
  ('MB_M274_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 400, 580, 0.6, 1.0, 'brake_pads_luxury', 3, NULL),
  ('MB_M274_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 400, 550, 0.9, 1.3, 'basic_service_premium', 3, NULL),
  ('TES_MODEL3_BEV', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 350, 550, 0.6, 1.0, 'brake_pads_luxury', 3, 'Regen braking dramatically extends pad life — many cars 100,000km+ on original pads.'),
  ('TES_MODEL3_BEV', (SELECT id FROM part_categories WHERE slug = 'brake_pads_rear'), 350, 550, 0.6, 1.0, 'brake_pads_luxury', 3, NULL),
  ('TES_MODEL3_BEV', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 200, 350, 0.5, 1.0, 'basic_service_mid', 3, 'Cabin filter, brake fluid, A/C desiccant. No engine oil. Tesla recommended interval longer than ICE.'),
  ('TOY_1MZFE_30_V6', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 800, 1100, 4.5, 6.0, 'cambelt_japanese_mid', 3, NULL),
  ('TOY_1MZFE_30_V6', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 230, 350, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('TOY_1MZFE_30_V6', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 230, 320, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('TOY_1MZFE_30_V6', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 400, 540, 1.4, 2.0, 'comprehensive_service_mid', 3, NULL),
  ('TOY_3MZFE_33_V6', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 850, 1150, 4.5, 6.0, 'cambelt_japanese_mid', 3, NULL),
  ('TOY_3MZFE_33_V6', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 240, 360, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('TOY_3MZFE_33_V6', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 240, 330, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('TOY_5VZFE_34_V6', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 850, 1200, 5.0, 7.0, 'cambelt_japanese_mid', 3, NULL),
  ('TOY_5VZFE_34_V6', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 240, 360, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('TOY_5VZFE_34_V6', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 230, 320, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('TOY_4AFE_7AFE_16_18', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 500, 750, 3.0, 4.5, 'cambelt_japanese_economy', 3, NULL),
  ('TOY_4AFE_7AFE_16_18', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 150, 230, 0.4, 0.7, 'brake_pads_economy', 3, NULL),
  ('TOY_4AFE_7AFE_16_18', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 150, 220, 0.5, 0.9, 'basic_service_economy', 3, NULL),
  ('TOY_1NR_2NR_13_15', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 160, 250, 0.4, 0.7, 'brake_pads_economy', 3, NULL),
  ('TOY_1NR_2NR_13_15', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 160, 230, 0.5, 0.9, 'basic_service_economy', 3, NULL),
  ('TOY_1JZ_25_I6', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 700, 1000, 4.0, 5.5, 'cambelt_japanese_mid', 3, NULL),
  ('TOY_1JZ_25_I6', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 240, 380, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('TOY_1JZ_25_I6', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 230, 320, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('TOY_2JZ_30_I6', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 750, 1100, 4.5, 6.0, 'cambelt_japanese_mid', 3, NULL),
  ('TOY_2JZ_30_I6', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 280, 420, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('TOY_2JZ_30_I6', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 240, 340, 0.7, 1.1, 'basic_service_premium', 3, NULL),
  ('TOY_1HZ_42_DIESEL_I6', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 1000, 1500, 5.0, 7.0, 'cambelt_japanese_mid', 3, NULL),
  ('TOY_1HZ_42_DIESEL_I6', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 280, 420, 0.7, 1.1, 'brake_pads_mid', 3, NULL),
  ('TOY_1HZ_42_DIESEL_I6', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 250, 350, 0.9, 1.3, 'basic_service_premium', 3, NULL),
  ('TOY_1KZTE_30_TDIESEL', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 900, 1300, 4.5, 6.0, 'cambelt_hilux_diesel_1kd_2kd', 3, NULL),
  ('TOY_1KZTE_30_TDIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 230, 350, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('TOY_1KZTE_30_TDIESEL', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 220, 310, 0.8, 1.2, 'basic_service_mid', 3, NULL),
  ('TOY_5LE_30_DIESEL', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 800, 1100, 4.0, 5.5, 'cambelt_hilux_diesel_1kd_2kd', 3, NULL),
  ('TOY_5LE_30_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 200, 320, 0.6, 1.0, 'brake_pads_economy', 3, NULL),
  ('TOY_5LE_30_DIESEL', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 200, 290, 0.8, 1.2, 'basic_service_economy', 3, NULL),
  ('HON_B_SERIES_16_18_20', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 600, 900, 3.5, 5.0, 'cambelt_japanese_economy', 3, NULL),
  ('HON_B_SERIES_16_18_20', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 200, 320, 0.5, 0.8, 'brake_pads_mid', 3, NULL),
  ('HON_B_SERIES_16_18_20', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 200, 280, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('HON_F_SERIES_20_22_23', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 600, 900, 3.5, 5.0, 'cambelt_japanese_economy', 3, NULL),
  ('HON_F_SERIES_20_22_23', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 200, 320, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('HON_F_SERIES_20_22_23', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 200, 280, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('HON_J_SERIES_V6', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 800, 1150, 4.5, 6.0, 'cambelt_japanese_mid', 3, NULL),
  ('HON_J_SERIES_V6', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 280, 420, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('HON_J_SERIES_V6', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 250, 340, 0.7, 1.1, 'basic_service_premium', 3, NULL),
  ('NIS_SR20_20', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 190, 290, 0.5, 0.8, 'brake_pads_mid', 3, NULL),
  ('NIS_SR20_20', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 200, 280, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('NIS_VQ25_VQ30_V6', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 260, 400, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('NIS_VQ25_VQ30_V6', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 240, 330, 0.7, 1.1, 'basic_service_premium', 3, NULL),
  ('NIS_YD25_25_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 240, 360, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('NIS_YD25_25_DIESEL', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 230, 320, 0.8, 1.2, 'basic_service_mid', 3, NULL),
  ('NIS_ZD30_30_DIESEL', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 900, 1300, 4.5, 6.0, 'cambelt_hilux_diesel_1kd_2kd', 3, NULL),
  ('NIS_ZD30_30_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 240, 360, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('NIS_ZD30_30_DIESEL', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 230, 320, 0.8, 1.2, 'basic_service_mid', 3, NULL),
  ('NIS_VK56_56_V8', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 320, 480, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('NIS_VK56_56_V8', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 280, 380, 0.8, 1.2, 'basic_service_premium', 3, NULL),
  ('MAZ_B6_BP_FS_LEGACY', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 500, 750, 3.0, 4.5, 'cambelt_japanese_economy', 3, NULL),
  ('MAZ_B6_BP_FS_LEGACY', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 160, 250, 0.4, 0.7, 'brake_pads_economy', 3, NULL),
  ('MAZ_B6_BP_FS_LEGACY', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 160, 230, 0.5, 0.9, 'basic_service_economy', 3, NULL),
  ('MAZ_13B_ROTARY', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 280, 420, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('MAZ_13B_ROTARY', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 250, 340, 0.7, 1.1, 'basic_service_mid', 3, 'Premix oil required if not running OMP. No cambelt — but apex seal life is the real maintenance concern.'),
  ('MAZ_13B_ROTARY', (SELECT id FROM part_categories WHERE slug = 'rotor_rebuild'), 6000, 12000, 25.0, 40.0, 'comprehensive_service_premium', 2, 'Full rebuild — apex seals, side seals, rotor housings. NZ specialist territory. Common at 80,000-150,000km.'),
  ('MIT_4G63_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 700, 1000, 4.0, 5.5, 'cambelt_japanese_mid', 3, NULL),
  ('MIT_4G63_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 280, 420, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('MIT_4G63_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 240, 330, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('MIT_6G72_6G74_V6', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 750, 1050, 4.5, 6.0, 'cambelt_japanese_mid', 3, NULL),
  ('MIT_6G72_6G74_V6', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 230, 350, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('MIT_6G72_6G74_V6', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 220, 300, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('MIT_4D56_25_DIESEL', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 850, 1200, 4.5, 6.0, 'cambelt_hilux_diesel_1kd_2kd', 3, NULL),
  ('MIT_4D56_25_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 220, 340, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('MIT_4D56_25_DIESEL', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 220, 310, 0.8, 1.2, 'basic_service_mid', 3, NULL),
  ('MIT_4M41_32_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 240, 360, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('MIT_4M41_32_DIESEL', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 240, 330, 0.8, 1.2, 'basic_service_mid', 3, NULL),
  ('MIT_4G15_4G18_15_16', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 500, 750, 3.0, 4.5, 'cambelt_japanese_economy', 3, NULL),
  ('MIT_4G15_4G18_15_16', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 150, 230, 0.4, 0.7, 'brake_pads_economy', 3, NULL),
  ('MIT_4G15_4G18_15_16', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 150, 220, 0.5, 0.9, 'basic_service_economy', 3, NULL),
  ('MIT_3A92_3B20_10_12', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 150, 220, 0.4, 0.7, 'brake_pads_economy', 3, NULL),
  ('MIT_3A92_3B20_10_12', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 150, 210, 0.5, 0.9, 'basic_service_economy', 3, NULL),
  ('MIT_IMIEV_BEV', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 180, 280, 0.4, 0.7, 'brake_pads_economy', 3, NULL),
  ('MIT_IMIEV_BEV', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 150, 220, 0.5, 0.9, 'basic_service_economy', 3, NULL),
  ('MIT_IMIEV_BEV', (SELECT id FROM part_categories WHERE slug = 'hv_battery_used'), 4000, 8000, 3.0, 5.0, 'hv_battery_leaf_24kwh_used', 2, 'i-MiEV 16kWh pack — very limited NZ replacement market'),
  ('SUB_EE20_20_DIESEL', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 1000, 1400, 5.5, 7.5, 'cambelt_japanese_mid', 3, NULL),
  ('SUB_EE20_20_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 240, 360, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('SUB_EE20_20_DIESEL', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 240, 330, 0.8, 1.2, 'basic_service_mid', 3, NULL),
  ('SUB_EZ30_EZ36_H6', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 280, 420, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('SUB_EZ30_EZ36_H6', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 260, 360, 0.8, 1.2, 'basic_service_premium', 3, NULL),
  ('VW_EA111_14_TSI', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 280, 420, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('VW_EA111_14_TSI', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 280, 380, 0.8, 1.2, 'basic_service_mid', 3, NULL),
  ('VW_EA113_20_TFSI', (SELECT id FROM part_categories WHERE slug = 'cambelt_full'), 1100, 1500, 4.5, 6.0, 'cambelt_euro_premium', 2, NULL),
  ('VW_EA113_20_TFSI', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 320, 480, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('VW_EA113_20_TFSI', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 320, 420, 0.8, 1.2, 'basic_service_premium', 3, NULL),
  ('AUDI_30_TDI_V6', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 420, 600, 0.6, 1.0, 'brake_pads_luxury', 3, NULL),
  ('AUDI_30_TDI_V6', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 400, 540, 0.9, 1.3, 'basic_service_premium', 3, NULL),
  ('AUDI_30_TDI_V6', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 600, 850, 1.6, 2.4, 'comprehensive_service_premium', 3, NULL),
  ('HOL_ALLOYTEC_36_V6', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 240, 360, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('HOL_ALLOYTEC_36_V6', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 220, 310, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('HOL_ALLOYTEC_36_V6', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 400, 540, 1.4, 2.0, 'comprehensive_service_mid', 3, NULL),
  ('HOL_ECOTEC_38_V6', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 200, 320, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('HOL_ECOTEC_38_V6', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 200, 290, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('HOL_LS_V8', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 380, 580, 0.6, 1.0, 'brake_pads_luxury', 3, NULL),
  ('HOL_LS_V8', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 260, 360, 0.7, 1.1, 'basic_service_premium', 3, NULL),
  ('FORD_BARRA_40_I6', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 220, 340, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('FORD_BARRA_40_I6', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 220, 310, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('LEX_2GRFSE_35_D4S', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 380, 560, 0.6, 1.0, 'brake_pads_luxury', 3, NULL),
  ('LEX_2GRFSE_35_D4S', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 320, 420, 0.8, 1.2, 'basic_service_premium', 3, NULL),
  ('LEX_2URGSE_50_V8', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 500, 750, 0.7, 1.1, 'brake_pads_luxury', 3, NULL),
  ('LEX_2URGSE_50_V8', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 420, 580, 0.9, 1.3, 'basic_service_premium', 3, NULL),
  ('SUZ_K6A_F6A_KEI', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 140, 220, 0.4, 0.7, 'brake_pads_economy', 3, NULL),
  ('SUZ_K6A_F6A_KEI', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 150, 220, 0.5, 0.9, 'basic_service_economy', 3, NULL),
  ('SUZ_K10C_10_TURBO', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 170, 260, 0.4, 0.7, 'brake_pads_economy', 3, NULL),
  ('SUZ_K10C_10_TURBO', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 170, 240, 0.5, 0.9, 'basic_service_economy', 3, NULL),
  ('DAI_KF_KEI', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 140, 220, 0.4, 0.7, 'brake_pads_economy', 3, NULL),
  ('DAI_KF_KEI', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 150, 220, 0.5, 0.9, 'basic_service_economy', 3, NULL),
  ('MG_SAIC_15_TURBO', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 180, 280, 0.5, 0.8, 'brake_pads_economy', 3, NULL),
  ('MG_SAIC_15_TURBO', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 180, 260, 0.6, 1.0, 'basic_service_economy', 3, NULL),
  ('BYD_BLADE_BEV', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 220, 340, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('BYD_BLADE_BEV', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 180, 260, 0.5, 0.9, 'basic_service_economy', 3, NULL),
  ('BYD_BLADE_BEV', (SELECT id FROM part_categories WHERE slug = 'hv_battery_replacement'), 18000, 30000, 4.0, 6.0, 'hv_battery_leaf_40kwh_upgrade', 1, 'BYD Blade LFP pack — out of warranty replacement pricing speculative. No mature NZ replacement market yet. Flag manual quote.'),
  ('GWM_4N20_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 220, 340, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('GWM_4N20_20_TURBO', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 220, 310, 0.7, 1.1, 'basic_service_mid', 3, NULL),
  ('LDV_MAXUS_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 220, 340, 0.6, 1.0, 'brake_pads_mid', 3, NULL),
  ('LDV_MAXUS_DIESEL', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 220, 310, 0.8, 1.2, 'basic_service_mid', 3, NULL),
  ('MB_OM651_21_DIESEL', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 400, 580, 0.6, 1.0, 'brake_pads_luxury', 3, NULL),
  ('MB_OM651_21_DIESEL', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 380, 520, 0.9, 1.3, 'basic_service_premium', 3, NULL),
  ('MB_OM651_21_DIESEL', (SELECT id FROM part_categories WHERE slug = 'comprehensive_service'), 580, 800, 1.6, 2.4, 'comprehensive_service_premium', 3, NULL),
  ('MB_M271_18_FORCED', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 380, 560, 0.6, 1.0, 'brake_pads_luxury', 3, NULL),
  ('MB_M271_18_FORCED', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 380, 500, 0.9, 1.3, 'basic_service_premium', 3, NULL),
  ('HKM_THETA_II_20_24', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 200, 320, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('HKM_THETA_II_20_24', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 200, 290, 0.7, 1.1, 'basic_service_economy', 3, NULL),
  ('HKM_LAMBDA_V6', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 280, 420, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('HKM_LAMBDA_V6', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 260, 360, 0.7, 1.1, 'basic_service_premium', 3, NULL),
  ('HKM_SMARTSTREAM_16_HYBRID', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 210, 320, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('HKM_SMARTSTREAM_16_HYBRID', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 200, 280, 0.6, 1.0, 'basic_service_mid', 3, NULL),
  ('HKM_SMARTSTREAM_16_HYBRID', (SELECT id FROM part_categories WHERE slug = 'hv_battery_refurb'), 2500, 4500, 3.0, 4.5, 'hv_battery_aqua_prius_g23_new', 2, 'Li-Po pack — newer chemistry than Toyota NiMH. Refurb market less developed.'),
  ('HKM_EV_BEV', (SELECT id FROM part_categories WHERE slug = 'brake_pads_front'), 280, 420, 0.5, 0.9, 'brake_pads_mid', 3, NULL),
  ('HKM_EV_BEV', (SELECT id FROM part_categories WHERE slug = 'basic_service'), 200, 320, 0.5, 1.0, 'basic_service_mid', 3, NULL)
) AS v(engine_family_id, category_id, total_job_low, total_job_high,
       hours_low, hours_high, source_anchor, confidence, notes)
WHERE v.category_id IS NOT NULL
ON CONFLICT (engine_family_id, category_id) DO NOTHING;

-- ef_parts_data rows: 324