-- ============================================================
-- TORQUED - Migration 042: Pricing moat (spark plugs, ignition coils, cambelt)
-- Engine-family-specific NZ GST-INCLUSIVE parts pricing, generated from the
-- reviewed dataset (Torqued_Pricing_Moat_REVIEW.xlsx). Calibrated to NZ retail
-- (Repco/Supercheap/Dayco), scaled per engine by cylinders, displacement, fuel
-- and segment tier. Manufacturer cambelt intervals from DB.
--
-- total_job = parts (GST-incl) + hours_high * 130 (platform ref rate). The
-- endpoint re-derives parts = total - hours_high * <mechanic rate>, matching the
-- existing ef_parts_data convention. Engine-specific rows OVERRIDE generic tier
-- estimates (ef_parts_data is checked before tier_parts_reference).
--
-- REQUIRES companion code change in server.ts (EF_SLUG_TO_SVC) mapping
-- 'spark_plugs' and 'ignition_coil' to their services, else plug/coil rows are
-- ignored by the customer endpoint.
--
-- Cambelt uses ON CONFLICT DO NOTHING: the 29 existing hand-curated rows are
-- untouched; only missing belt families are added. Idempotent.
--
-- HELD FOR REVIEW (not included): chain-timing reference pricing (chains not
-- scheduled - kept as a 1-business-hour quote) and standalone water-pump pricing.
-- ============================================================

-- Cambelt (belt/wet-belt) (35 families) -> category 'cambelt_full'
INSERT INTO ef_parts_data (engine_family_id, category_id, total_job_low, total_job_high, hours_low, hours_high, source_anchor, confidence, notes)
SELECT v.* FROM (VALUES
  ('FORD_P4AT_22_TDCI', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1400, 1605, 6, 9, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('FORD_P5AT_32_TDCI', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1510, 1815, 6, 9, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('HON_B_SERIES_16_18_20', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 760, 915, 3, 4.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('HON_F_SERIES_20_22_23', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 760, 915, 3, 4.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('HON_J_SERIES_V6', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1180, 1600, 4, 5.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('HKM_G4FC_16', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 725, 850, 3, 4.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('LR_AJ_V6_30_DIESEL', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1960, 2670, 6, 9, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('LR_INGENIUM_20_DIESEL', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1550, 1890, 6, 9, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('MAZ_B6_BP_FS_LEGACY', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 725, 850, 3, 4.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('MIT_4D56_25_DIESEL', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1010, 1215, 4, 6, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('MIT_4G15_4G18_15_16', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 725, 850, 3, 4.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('MIT_4G63_20_TURBO', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 810, 1015, 3, 4.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('MIT_6G72_6G74_V6', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1075, 1400, 4, 5.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('NIS_ZD30_30_DIESEL', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1010, 1215, 4, 6, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('SUB_EE20_20_DIESEL', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1010, 1215, 4, 6, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('SUB_EJ20_20_TURBO', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 810, 1015, 3, 4.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('SUB_EJ25_25_BOXER_BELT', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 760, 915, 3, 4.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('TOY_1HZ_42_DIESEL_I6', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1385, 1930, 4, 6, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('TOY_1JZ_25_I6', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1180, 1600, 4, 5.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('TOY_1KDFTV_30_DIESEL', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1010, 1215, 4, 6, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('TOY_1KZTE_30_TDIESEL', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1010, 1215, 4, 6, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('TOY_1MZFE_30_V6', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1075, 1400, 4, 5.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('TOY_2JZ_30_I6', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1180, 1600, 4, 5.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('TOY_2KDFTV_25_DIESEL', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1010, 1215, 4, 6, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('TOY_3MZFE_33_V6', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1075, 1400, 4, 5.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('TOY_4AFE_7AFE_16_18', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 725, 850, 3, 4.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('TOY_5LE_30_DIESEL', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 960, 1120, 4, 6, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('TOY_5VZFE_34_V6', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1075, 1400, 4, 5.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('VW_EA113_20_TFSI', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 810, 1015, 3, 4.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('VW_EA189_20_TDI', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1010, 1215, 4, 6, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('VW_EA211_10_TSI_3CYL', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 725, 850, 3, 4.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('VW_EA211_14_TSI', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 760, 915, 3, 4.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('VW_EA211_GTE_PHEV', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 810, 1015, 3, 4.5, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('VOLVO_VEA_20_DIESEL', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1550, 1890, 6, 9, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl'),
  ('VOLVO_VEA_20_PETROL', (SELECT id FROM part_categories WHERE slug='cambelt_full'), 1465, 1730, 6, 9, 'moat_nz_gst_incl', 3, 'Cambelt kit incl tensioner+idlers; NZ GST-incl')
) AS v(engine_family_id, category_id, total_job_low, total_job_high, hours_low, hours_high, source_anchor, confidence, notes)
ON CONFLICT (engine_family_id, category_id) DO NOTHING;

-- Spark plugs (95 families) -> category 'spark_plugs'
INSERT INTO ef_parts_data (engine_family_id, category_id, total_job_low, total_job_high, hours_low, hours_high, source_anchor, confidence, notes)
SELECT v.* FROM (VALUES
  ('AUDI_EA839_30_TFSI_V6', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 529, 637, 1.5, 2.5, 'moat_nz_gst_incl', 2, '6x Iridium (turbo/perf); set NZ GST-incl'),
  ('BMW_B48_20_TURBO', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 266, 338, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium (turbo/perf); set NZ GST-incl'),
  ('BMW_B58_30_TURBO', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 529, 637, 1.5, 2.5, 'moat_nz_gst_incl', 2, '6x Iridium (turbo/perf); set NZ GST-incl'),
  ('BMW_N20_20_TURBO', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 266, 338, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium (turbo/perf); set NZ GST-incl'),
  ('BYD_DMI_15_HYBRID', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('CHERY_15_TURBO', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('DAI_KF_KEI', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 214, 262, 0.5, 1, 'moat_nz_gst_incl', 2, '3x Iridium; set NZ GST-incl'),
  ('FORD_BARRA_40_I6', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 493, 589, 1.5, 2.5, 'moat_nz_gst_incl', 2, '6x Iridium; set NZ GST-incl'),
  ('GWM_4N20_20_TURBO', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('HOL_ALLOYTEC_36_V6', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 493, 589, 1.5, 2.5, 'moat_nz_gst_incl', 2, '6x Iridium; set NZ GST-incl'),
  ('HOL_ECOTEC_38_V6', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 493, 589, 1.5, 2.5, 'moat_nz_gst_incl', 2, '6x Iridium; set NZ GST-incl'),
  ('HOL_LS_V8', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 597, 741, 1.5, 2.5, 'moat_nz_gst_incl', 2, '8x Iridium (turbo/perf); set NZ GST-incl'),
  ('HON_B_SERIES_16_18_20', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 3, '4x Iridium; set NZ GST-incl'),
  ('HON_F_SERIES_20_22_23', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 3, '4x Iridium; set NZ GST-incl'),
  ('HON_J_SERIES_V6', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 529, 637, 1.5, 2.5, 'moat_nz_gst_incl', 3, '6x Iridium (turbo/perf); set NZ GST-incl'),
  ('HON_K20_20', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('HON_K24_24', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('HON_L13_L15_13_15', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('HON_L15B_15T', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('HON_LDA_IMA_HYBRID', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('HON_LEB_15_IDCD_HYBRID', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('HON_R18A_18', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('HKM_G4FC_16', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 3, '4x Iridium; set NZ GST-incl'),
  ('HKM_G4FG_G4NA_CHAIN', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('HKM_LAMBDA_V6', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 529, 637, 1.5, 2.5, 'moat_nz_gst_incl', 2, '6x Iridium (turbo/perf); set NZ GST-incl'),
  ('HKM_SMARTSTREAM_16_HYBRID', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('HKM_THETA_II_20_24', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('LR_50_SC_V8', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 597, 741, 1.5, 2.5, 'moat_nz_gst_incl', 2, '8x Iridium (turbo/perf); set NZ GST-incl'),
  ('LR_INGENIUM_20_PETROL', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 266, 338, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium (turbo/perf); set NZ GST-incl'),
  ('LEX_2GRFSE_35_D4S', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 529, 637, 1.5, 2.5, 'moat_nz_gst_incl', 2, '6x Iridium (turbo/perf); set NZ GST-incl'),
  ('LEX_2URGSE_50_V8', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 597, 741, 1.5, 2.5, 'moat_nz_gst_incl', 2, '8x Iridium (turbo/perf); set NZ GST-incl'),
  ('MG_SAIC_15_TURBO', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('MAZ_13B_ROTARY', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 266, 338, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium (turbo/perf); set NZ GST-incl'),
  ('MAZ_B6_BP_FS_LEGACY', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 194, 250, 0.5, 1, 'moat_nz_gst_incl', 3, '4x Platinum; set NZ GST-incl'),
  ('MAZ_SKYACTIVG_15', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('MAZ_SKYACTIVG_20', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('MAZ_SKYACTIVG_25', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('MAZ_ZY_VE_15', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('MB_M256_30_TURBO_MHEV', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 529, 637, 1.5, 2.5, 'moat_nz_gst_incl', 2, '6x Iridium (turbo/perf); set NZ GST-incl'),
  ('MB_M271_18_FORCED', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 266, 338, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium (turbo/perf); set NZ GST-incl'),
  ('MB_M274_20_TURBO', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 266, 338, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium (turbo/perf); set NZ GST-incl'),
  ('MINI_B38_15_TURBO', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 232, 286, 0.5, 1, 'moat_nz_gst_incl', 2, '3x Iridium (turbo/perf); set NZ GST-incl'),
  ('MINI_PRINCE_16', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 266, 338, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium (turbo/perf); set NZ GST-incl'),
  ('MIT_3A92_3B20_10_12', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 214, 262, 0.5, 1, 'moat_nz_gst_incl', 2, '3x Iridium; set NZ GST-incl'),
  ('MIT_4B11_4B12_20_24', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('MIT_4G15_4G18_15_16', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 194, 250, 0.5, 1, 'moat_nz_gst_incl', 3, '4x Platinum; set NZ GST-incl'),
  ('MIT_4G63_20_TURBO', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 194, 250, 0.5, 1, 'moat_nz_gst_incl', 3, '4x Platinum; set NZ GST-incl'),
  ('MIT_6G72_6G74_V6', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 493, 589, 1.5, 2.5, 'moat_nz_gst_incl', 3, '6x Iridium; set NZ GST-incl'),
  ('MIT_OUTLANDER_PHEV_24', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('NIS_HR15DE_15', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('NIS_MR18DE_18', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('NIS_MR20DE_20', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('NIS_QR25DE_25', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('NIS_SR20_20', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('NIS_VK56_56_V8', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 597, 741, 1.5, 2.5, 'moat_nz_gst_incl', 2, '8x Iridium (turbo/perf); set NZ GST-incl'),
  ('NIS_VQ25_VQ30_V6', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 529, 637, 1.5, 2.5, 'moat_nz_gst_incl', 2, '6x Iridium (turbo/perf); set NZ GST-incl'),
  ('NIS_VQ35DE_35_V6', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 529, 637, 1.5, 2.5, 'moat_nz_gst_incl', 2, '6x Iridium (turbo/perf); set NZ GST-incl'),
  ('SUB_EJ20_20_TURBO', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 194, 250, 0.5, 1, 'moat_nz_gst_incl', 3, '4x Platinum; set NZ GST-incl'),
  ('SUB_EJ25_25_BOXER_BELT', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 194, 250, 0.5, 1, 'moat_nz_gst_incl', 3, '4x Platinum; set NZ GST-incl'),
  ('SUB_EZ30_EZ36_H6', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 529, 637, 1.5, 2.5, 'moat_nz_gst_incl', 2, '6x Iridium (turbo/perf); set NZ GST-incl'),
  ('SUB_FB20_20_CHAIN', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('SUB_FB25_25_CHAIN', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('SUZ_K10C_10_TURBO', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 214, 262, 0.5, 1, 'moat_nz_gst_incl', 2, '3x Iridium; set NZ GST-incl'),
  ('SUZ_K12B_12', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('SUZ_K14_14', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('SUZ_K6A_F6A_KEI', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 214, 262, 0.5, 1, 'moat_nz_gst_incl', 2, '3x Iridium; set NZ GST-incl'),
  ('SUZ_M16A_16', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('TOY_1AZFE_20', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('TOY_1GRFE_40_V6', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 529, 637, 1.5, 2.5, 'moat_nz_gst_incl', 2, '6x Iridium (turbo/perf); set NZ GST-incl'),
  ('TOY_1JZ_25_I6', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 529, 637, 1.5, 2.5, 'moat_nz_gst_incl', 3, '6x Iridium (turbo/perf); set NZ GST-incl'),
  ('TOY_1KRFE_10', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 214, 262, 0.5, 1, 'moat_nz_gst_incl', 2, '3x Iridium; set NZ GST-incl'),
  ('TOY_1MZFE_30_V6', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 493, 589, 1.5, 2.5, 'moat_nz_gst_incl', 3, '6x Iridium; set NZ GST-incl'),
  ('TOY_1NR_2NR_13_15', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('TOY_1NZFE_15', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('TOY_1NZFXE_15_HYBRID', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('TOY_1ZRFE_16', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('TOY_2ARFE_25', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('TOY_2ARFXE_25_HYBRID', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('TOY_2AZFE_24', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('TOY_2GRFE_35_V6', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 529, 637, 1.5, 2.5, 'moat_nz_gst_incl', 2, '6x Iridium (turbo/perf); set NZ GST-incl'),
  ('TOY_2JZ_30_I6', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 529, 637, 1.5, 2.5, 'moat_nz_gst_incl', 3, '6x Iridium (turbo/perf); set NZ GST-incl'),
  ('TOY_2NZFE_13', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('TOY_2ZRFE_18', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('TOY_2ZRFXE_18_HYBRID', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('TOY_3MZFE_33_V6', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 493, 589, 1.5, 2.5, 'moat_nz_gst_incl', 3, '6x Iridium; set NZ GST-incl'),
  ('TOY_4AFE_7AFE_16_18', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 194, 250, 0.5, 1, 'moat_nz_gst_incl', 3, '4x Platinum; set NZ GST-incl'),
  ('TOY_5VZFE_34_V6', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 493, 589, 1.5, 2.5, 'moat_nz_gst_incl', 3, '6x Iridium; set NZ GST-incl'),
  ('TOY_A25AFXS_25_HYBRID', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('VW_EA111_14_TSI', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium; set NZ GST-incl'),
  ('VW_EA113_20_TFSI', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 266, 338, 0.5, 1, 'moat_nz_gst_incl', 3, '4x Iridium (turbo/perf); set NZ GST-incl'),
  ('VW_EA211_10_TSI_3CYL', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 214, 262, 0.5, 1, 'moat_nz_gst_incl', 3, '3x Iridium; set NZ GST-incl'),
  ('VW_EA211_14_TSI', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 242, 306, 0.5, 1, 'moat_nz_gst_incl', 3, '4x Iridium; set NZ GST-incl'),
  ('VW_EA211_GTE_PHEV', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 266, 338, 0.5, 1, 'moat_nz_gst_incl', 3, '4x Iridium (turbo/perf); set NZ GST-incl'),
  ('VW_EA888_20_TSI', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 266, 338, 0.5, 1, 'moat_nz_gst_incl', 2, '4x Iridium (turbo/perf); set NZ GST-incl'),
  ('VOLVO_VEA_20_PETROL', (SELECT id FROM part_categories WHERE slug='spark_plugs'), 266, 338, 0.5, 1, 'moat_nz_gst_incl', 3, '4x Iridium (turbo/perf); set NZ GST-incl')
) AS v(engine_family_id, category_id, total_job_low, total_job_high, hours_low, hours_high, source_anchor, confidence, notes)
ON CONFLICT (engine_family_id, category_id) DO NOTHING;

-- Ignition coils (95 families) -> category 'ignition_coil'
INSERT INTO ef_parts_data (engine_family_id, category_id, total_job_low, total_job_high, hours_low, hours_high, source_anchor, confidence, notes)
SELECT v.* FROM (VALUES
  ('AUDI_EA839_30_TFSI_V6', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 980, 1460, 1, 2, 'moat_nz_gst_incl', 2, '6x COP coils; set NZ GST-incl'),
  ('BMW_B48_20_TURBO', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 642, 962, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('BMW_B58_30_TURBO', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 980, 1460, 1, 2, 'moat_nz_gst_incl', 2, '6x COP coils; set NZ GST-incl'),
  ('BMW_N20_20_TURBO', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 642, 962, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('BYD_DMI_15_HYBRID', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('CHERY_15_TURBO', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('DAI_KF_KEI', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 297, 402, 0.5, 1.25, 'moat_nz_gst_incl', 2, '3x COP coils; set NZ GST-incl'),
  ('FORD_BARRA_40_I6', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 620, 920, 1, 2, 'moat_nz_gst_incl', 2, '6x COP coils; set NZ GST-incl'),
  ('GWM_4N20_20_TURBO', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('HOL_ALLOYTEC_36_V6', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 620, 920, 1, 2, 'moat_nz_gst_incl', 2, '6x COP coils; set NZ GST-incl'),
  ('HOL_ECOTEC_38_V6', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 620, 920, 1, 2, 'moat_nz_gst_incl', 2, '6x COP coils; set NZ GST-incl'),
  ('HOL_LS_V8', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 980, 1540, 1, 2, 'moat_nz_gst_incl', 2, '8x COP coils; set NZ GST-incl'),
  ('HON_B_SERIES_16_18_20', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 3, '4x COP coils; set NZ GST-incl'),
  ('HON_F_SERIES_20_22_23', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 3, '4x COP coils; set NZ GST-incl'),
  ('HON_J_SERIES_V6', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 800, 1220, 1, 2, 'moat_nz_gst_incl', 3, '6x COP coils; set NZ GST-incl'),
  ('HON_K20_20', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('HON_K24_24', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('HON_L13_L15_13_15', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('HON_L15B_15T', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('HON_LDA_IMA_HYBRID', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('HON_LEB_15_IDCD_HYBRID', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('HON_R18A_18', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('HKM_G4FC_16', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 3, '4x COP coils; set NZ GST-incl'),
  ('HKM_G4FG_G4NA_CHAIN', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('HKM_LAMBDA_V6', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 800, 1220, 1, 2, 'moat_nz_gst_incl', 2, '6x COP coils; set NZ GST-incl'),
  ('HKM_SMARTSTREAM_16_HYBRID', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('HKM_THETA_II_20_24', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('LR_50_SC_V8', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 1220, 1860, 1, 2, 'moat_nz_gst_incl', 2, '8x COP coils; set NZ GST-incl'),
  ('LR_INGENIUM_20_PETROL', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 642, 962, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('LEX_2GRFSE_35_D4S', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 980, 1460, 1, 2, 'moat_nz_gst_incl', 2, '6x COP coils; set NZ GST-incl'),
  ('LEX_2URGSE_50_V8', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 1220, 1860, 1, 2, 'moat_nz_gst_incl', 2, '8x COP coils; set NZ GST-incl'),
  ('MG_SAIC_15_TURBO', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('MAZ_13B_ROTARY', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 522, 802, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('MAZ_B6_BP_FS_LEGACY', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 3, '4x COP coils; set NZ GST-incl'),
  ('MAZ_SKYACTIVG_15', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('MAZ_SKYACTIVG_20', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('MAZ_SKYACTIVG_25', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('MAZ_ZY_VE_15', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('MB_M256_30_TURBO_MHEV', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 980, 1460, 1, 2, 'moat_nz_gst_incl', 2, '6x COP coils; set NZ GST-incl'),
  ('MB_M271_18_FORCED', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 642, 962, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('MB_M274_20_TURBO', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 642, 962, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('MINI_B38_15_TURBO', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 432, 642, 0.5, 1.25, 'moat_nz_gst_incl', 2, '3x COP coils; set NZ GST-incl'),
  ('MINI_PRINCE_16', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 522, 802, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('MIT_3A92_3B20_10_12', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 297, 402, 0.5, 1.25, 'moat_nz_gst_incl', 2, '3x COP coils; set NZ GST-incl'),
  ('MIT_4B11_4B12_20_24', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('MIT_4G15_4G18_15_16', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 3, '4x COP coils; set NZ GST-incl'),
  ('MIT_4G63_20_TURBO', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 522, 802, 0.5, 1.25, 'moat_nz_gst_incl', 3, '4x COP coils; set NZ GST-incl'),
  ('MIT_6G72_6G74_V6', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 620, 920, 1, 2, 'moat_nz_gst_incl', 3, '6x COP coils; set NZ GST-incl'),
  ('MIT_OUTLANDER_PHEV_24', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('NIS_HR15DE_15', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('NIS_MR18DE_18', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('NIS_MR20DE_20', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('NIS_QR25DE_25', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('NIS_SR20_20', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('NIS_VK56_56_V8', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 980, 1540, 1, 2, 'moat_nz_gst_incl', 2, '8x COP coils; set NZ GST-incl'),
  ('NIS_VQ25_VQ30_V6', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 800, 1220, 1, 2, 'moat_nz_gst_incl', 2, '6x COP coils; set NZ GST-incl'),
  ('NIS_VQ35DE_35_V6', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 800, 1220, 1, 2, 'moat_nz_gst_incl', 2, '6x COP coils; set NZ GST-incl'),
  ('SUB_EJ20_20_TURBO', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 522, 802, 0.5, 1.25, 'moat_nz_gst_incl', 3, '4x COP coils; set NZ GST-incl'),
  ('SUB_EJ25_25_BOXER_BELT', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 3, '4x COP coils; set NZ GST-incl'),
  ('SUB_EZ30_EZ36_H6', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 800, 1220, 1, 2, 'moat_nz_gst_incl', 2, '6x COP coils; set NZ GST-incl'),
  ('SUB_FB20_20_CHAIN', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('SUB_FB25_25_CHAIN', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('SUZ_K10C_10_TURBO', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 297, 402, 0.5, 1.25, 'moat_nz_gst_incl', 2, '3x COP coils; set NZ GST-incl'),
  ('SUZ_K12B_12', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('SUZ_K14_14', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('SUZ_K6A_F6A_KEI', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 297, 402, 0.5, 1.25, 'moat_nz_gst_incl', 2, '3x COP coils; set NZ GST-incl'),
  ('SUZ_M16A_16', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('TOY_1AZFE_20', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('TOY_1GRFE_40_V6', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 800, 1220, 1, 2, 'moat_nz_gst_incl', 2, '6x COP coils; set NZ GST-incl'),
  ('TOY_1JZ_25_I6', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 800, 1220, 1, 2, 'moat_nz_gst_incl', 3, '6x COP coils; set NZ GST-incl'),
  ('TOY_1KRFE_10', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 297, 402, 0.5, 1.25, 'moat_nz_gst_incl', 2, '3x COP coils; set NZ GST-incl'),
  ('TOY_1MZFE_30_V6', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 620, 920, 1, 2, 'moat_nz_gst_incl', 3, '6x COP coils; set NZ GST-incl'),
  ('TOY_1NR_2NR_13_15', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('TOY_1NZFE_15', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('TOY_1NZFXE_15_HYBRID', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('TOY_1ZRFE_16', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('TOY_2ARFE_25', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('TOY_2ARFXE_25_HYBRID', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('TOY_2AZFE_24', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('TOY_2GRFE_35_V6', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 800, 1220, 1, 2, 'moat_nz_gst_incl', 2, '6x COP coils; set NZ GST-incl'),
  ('TOY_2JZ_30_I6', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 800, 1220, 1, 2, 'moat_nz_gst_incl', 3, '6x COP coils; set NZ GST-incl'),
  ('TOY_2NZFE_13', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('TOY_2ZRFE_18', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('TOY_2ZRFXE_18_HYBRID', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('TOY_3MZFE_33_V6', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 620, 920, 1, 2, 'moat_nz_gst_incl', 3, '6x COP coils; set NZ GST-incl'),
  ('TOY_4AFE_7AFE_16_18', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 482, 0.5, 1.25, 'moat_nz_gst_incl', 3, '4x COP coils; set NZ GST-incl'),
  ('TOY_5VZFE_34_V6', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 620, 920, 1, 2, 'moat_nz_gst_incl', 3, '6x COP coils; set NZ GST-incl'),
  ('TOY_A25AFXS_25_HYBRID', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('VW_EA111_14_TSI', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('VW_EA113_20_TFSI', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 522, 802, 0.5, 1.25, 'moat_nz_gst_incl', 3, '4x COP coils; set NZ GST-incl'),
  ('VW_EA211_10_TSI_3CYL', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 342, 492, 0.5, 1.25, 'moat_nz_gst_incl', 3, '3x COP coils; set NZ GST-incl'),
  ('VW_EA211_14_TSI', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 402, 602, 0.5, 1.25, 'moat_nz_gst_incl', 3, '4x COP coils; set NZ GST-incl'),
  ('VW_EA211_GTE_PHEV', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 522, 802, 0.5, 1.25, 'moat_nz_gst_incl', 3, '4x COP coils; set NZ GST-incl'),
  ('VW_EA888_20_TSI', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 522, 802, 0.5, 1.25, 'moat_nz_gst_incl', 2, '4x COP coils; set NZ GST-incl'),
  ('VOLVO_VEA_20_PETROL', (SELECT id FROM part_categories WHERE slug='ignition_coil'), 642, 962, 0.5, 1.25, 'moat_nz_gst_incl', 3, '4x COP coils; set NZ GST-incl')
) AS v(engine_family_id, category_id, total_job_low, total_job_high, hours_low, hours_high, source_anchor, confidence, notes)
ON CONFLICT (engine_family_id, category_id) DO NOTHING;
