-- ============================================================
-- TORQUED - Migration 043: Pricing moat (water pump + transmission)
-- Engine-family-specific NZ GST-INCLUSIVE pricing from the reviewed dataset
-- (Torqued_WaterPump_Transmission_REVIEW.xlsx). Makes most bookings instant-
-- priced so few users hit the 1-business-hour quote.
--   water_pump_standalone: pump + thermostat/housing + coolant refill. Belt-
--     driven pumps carry cambelt-sized labour (frontend nudges "do with cambelt").
--   transmission_service: fluid (capacity x NZ $/L) + filter/gasket kit. Only the
--     105 families with known fluid type+capacity; the rest stay quote-only.
-- total_job = parts (GST-incl) + hours_high * 130 (platform ref rate), matching
-- the ef_parts_data convention.
-- REQUIRES server.ts EF_SLUG_TO_SVC mapping water_pump_standalone->water_pump and
-- transmission_service->transmission. Idempotent.
-- ============================================================

-- Water pump (standalone) (125 families) -> category 'water_pump_standalone'
INSERT INTO ef_parts_data (engine_family_id, category_id, total_job_low, total_job_high, hours_low, hours_high, source_anchor, confidence, notes)
SELECT v.* FROM (VALUES
  ('AUDI_30_TDI_V6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 935, 1585, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('AUDI_EA839_30_TFSI_V6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 860, 1420, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('BMW_B47_20_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 690, 1210, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('BMW_B48_20_TURBO', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 635, 1085, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('BMW_B58_30_TURBO', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 855, 1410, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('BMW_N20_20_TURBO', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 635, 1085, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('BMW_N57_30_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 925, 1570, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('BYD_DMI_15_HYBRID', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 520, 795, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('CHERY_15_TURBO', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 490, 720, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('DAI_KF_KEI', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 470, 685, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('FORD_BARRA_40_I6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 715, 1060, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('FORD_P4AT_22_TDCI', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 1405, 1725, 6, 9, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('FORD_P5AT_32_TDCI', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 1445, 1805, 6, 9, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('FORD_YN2S_20_BITURBO', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 625, 1045, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('GWM_4N20_20_TURBO', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 520, 795, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('GWM_GW4D20_20_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 570, 900, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('HOL_ALLOYTEC_36_V6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 700, 1035, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('HOL_ECOTEC_38_V6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 700, 1035, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('HOL_LS_V8', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 750, 1170, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('HON_B_SERIES_16_18_20', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 770, 1040, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('HON_F_SERIES_20_22_23', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 790, 1075, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('HON_J_SERIES_V6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 1000, 1405, 4, 5.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('HON_K20_20', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 515, 790, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('HON_K24_24', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 515, 790, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('HON_L13_L15_13_15', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 480, 705, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('HON_L15B_15T', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 510, 780, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('HON_LDA_IMA_HYBRID', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 530, 815, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('HON_LEB_15_IDCD_HYBRID', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 510, 775, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('HON_R18A_18', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 480, 705, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('HKM_D4HA_20_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 570, 900, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('HKM_G4FC_16', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 740, 965, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('HKM_G4FG_G4NA_CHAIN', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 485, 710, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('HKM_LAMBDA_V6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 750, 1170, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('HKM_SMARTSTREAM_16_HYBRID', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 510, 780, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('HKM_THETA_II_20_24', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 520, 795, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('ISU_4JJ1_30_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 595, 950, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('LDV_MAXUS_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 570, 900, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('LR_50_SC_V8', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 890, 1480, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('LR_AJ_V6_30_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 1660, 2320, 6, 9, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('LR_INGENIUM_20_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 1550, 2080, 6, 9, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('LR_INGENIUM_20_PETROL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 655, 1120, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('LEX_2GRFSE_35_D4S', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 830, 1360, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('LEX_2URGSE_50_V8', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 830, 1360, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MG_SAIC_15_TURBO', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 485, 710, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MAZ_13B_ROTARY', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 560, 905, 1.5, 2.5, 'moat_nz_gst_incl', 2, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MAZ_B6_BP_FS_LEGACY', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 745, 970, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('MAZ_SKYACTIVD_22', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 575, 915, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MAZ_SKYACTIVG_15', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 495, 730, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MAZ_SKYACTIVG_20', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 530, 815, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MAZ_SKYACTIVG_25', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 535, 825, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MAZ_ZY_VE_15', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 490, 720, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MB_M256_30_TURBO_MHEV', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 860, 1420, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MB_M271_18_FORCED', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 640, 1095, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MB_M274_20_TURBO', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 640, 1095, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MB_OM651_21_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 705, 1235, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MB_OM654_20_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 700, 1225, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MINI_B38_15_TURBO', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 565, 915, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MINI_PRINCE_16', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 565, 915, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MIT_3A92_3B20_10_12', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 500, 735, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MIT_4B11_4B12_20_24', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 525, 805, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MIT_4D56_25_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 840, 1185, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('MIT_4G15_4G18_15_16', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 760, 995, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('MIT_4G63_20_TURBO', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 820, 1165, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('MIT_4M41_32_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 595, 950, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MIT_4N15_24_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 580, 925, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('MIT_6G72_6G74_V6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 960, 1295, 4, 5.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('MIT_OUTLANDER_PHEV_24', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 525, 805, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('NIS_HR15DE_15', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 490, 720, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('NIS_MR18DE_18', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 500, 735, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('NIS_MR20DE_20', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 535, 825, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('NIS_QR25DE_25', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 540, 830, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('NIS_SR20_20', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 525, 805, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('NIS_VK56_56_V8', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 780, 1220, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('NIS_VQ25_VQ30_V6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 755, 1175, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('NIS_VQ35DE_35_V6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 760, 1185, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('NIS_YD25_25_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 590, 940, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('NIS_ZD30_30_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 855, 1210, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('SUB_EE20_20_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 820, 1140, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('SUB_EJ20_20_TURBO', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 820, 1165, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('SUB_EJ25_25_BOXER_BELT', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 790, 1075, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('SUB_EZ30_EZ36_H6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 760, 1185, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('SUB_FB20_20_CHAIN', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 495, 730, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('SUB_FB25_25_CHAIN', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 530, 815, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('SUZ_K10C_10_TURBO', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 500, 735, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('SUZ_K12B_12', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 475, 695, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('SUZ_K14_14', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 510, 780, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('SUZ_K6A_F6A_KEI', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 470, 685, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('SUZ_M16A_16', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 485, 710, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('TOY_1AZFE_20', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 500, 735, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('TOY_1GDFTV_28_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 600, 960, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('TOY_1GRFE_40_V6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 775, 1210, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('TOY_1HZ_42_DIESEL_I6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 1130, 1670, 4, 5.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('TOY_1JZ_25_I6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 1025, 1455, 4, 5.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('TOY_1KDFTV_30_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 860, 1220, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('TOY_1KRFE_10', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 485, 710, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('TOY_1KZTE_30_TDIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 845, 1195, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('TOY_1MZFE_30_V6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 960, 1295, 4, 5.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('TOY_1NR_2NR_13_15', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 490, 720, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('TOY_1NZFE_15', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 495, 730, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('TOY_1NZFXE_15_HYBRID', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 525, 805, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('TOY_1ZRFE_16', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 495, 730, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('TOY_2ARFE_25', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 535, 825, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('TOY_2ARFXE_25_HYBRID', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 535, 825, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('TOY_2AZFE_24', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 535, 825, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('TOY_2GDFTV_24_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 590, 940, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('TOY_2GRFE_35_V6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 755, 1175, 2.5, 3.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('TOY_2JZ_30_I6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 1030, 1460, 4, 5.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('TOY_2KDFTV_25_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 845, 1195, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('TOY_2NZFE_13', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 490, 720, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('TOY_2ZRFE_18', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 495, 730, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('TOY_2ZRFXE_18_HYBRID', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 525, 805, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('TOY_3MZFE_33_V6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 965, 1305, 4, 5.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('TOY_4AFE_7AFE_16_18', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 755, 990, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('TOY_5LE_30_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 815, 1110, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('TOY_5VZFE_34_V6', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 975, 1330, 4, 5.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('TOY_A25AFXS_25_HYBRID', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 515, 790, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('VW_EA111_14_TSI', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 535, 825, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('VW_EA113_20_TFSI', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 845, 1210, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('VW_EA189_20_TDI', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 830, 1160, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('VW_EA211_10_TSI_3CYL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 790, 1075, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('VW_EA211_14_TSI', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 790, 1075, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('VW_EA211_GTE_PHEV', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 830, 1185, 3, 4.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('VW_EA888_20_TSI', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 585, 950, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; standalone; NZ GST-incl'),
  ('VOLVO_VEA_20_DIESEL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 1550, 2080, 6, 9, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl'),
  ('VOLVO_VEA_20_PETROL', (SELECT id FROM part_categories WHERE slug='water_pump_standalone'), 1500, 1965, 6, 9, 'moat_nz_gst_incl', 3, 'WP+thermostat+coolant; belt-driven (do w/ cambelt); NZ GST-incl')
) AS v(engine_family_id, category_id, total_job_low, total_job_high, hours_low, hours_high, source_anchor, confidence, notes)
ON CONFLICT (engine_family_id, category_id) DO NOTHING;

-- Transmission service (105 families) -> category 'transmission_service'
INSERT INTO ef_parts_data (engine_family_id, category_id, total_job_low, total_job_high, hours_low, hours_high, source_anchor, confidence, notes)
SELECT v.* FROM (VALUES
  ('AUDI_30_TDI_V6', (SELECT id FROM part_categories WHERE slug='transmission_service'), 355, 535, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 8L drain+fill; NZ GST-incl'),
  ('AUDI_EA839_30_TFSI_V6', (SELECT id FROM part_categories WHERE slug='transmission_service'), 355, 535, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 8L drain+fill; NZ GST-incl'),
  ('BMW_B47_20_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 355, 535, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 8L drain+fill; NZ GST-incl'),
  ('BMW_B48_20_TURBO', (SELECT id FROM part_categories WHERE slug='transmission_service'), 355, 535, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 8L drain+fill; NZ GST-incl'),
  ('BMW_B58_30_TURBO', (SELECT id FROM part_categories WHERE slug='transmission_service'), 355, 535, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 8L drain+fill; NZ GST-incl'),
  ('BMW_N20_20_TURBO', (SELECT id FROM part_categories WHERE slug='transmission_service'), 355, 535, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 8L drain+fill; NZ GST-incl'),
  ('BMW_N57_30_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 355, 535, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 8L drain+fill; NZ GST-incl'),
  ('CHERY_15_TURBO', (SELECT id FROM part_categories WHERE slug='transmission_service'), 335, 490, 1, 1.5, 'moat_nz_gst_incl', 3, 'CVT fluid 4.5L drain+fill; NZ GST-incl'),
  ('DAI_KF_KEI', (SELECT id FROM part_categories WHERE slug='transmission_service'), 330, 475, 1, 1.5, 'moat_nz_gst_incl', 3, 'CVT fluid 4L drain+fill; NZ GST-incl'),
  ('FORD_BARRA_40_I6', (SELECT id FROM part_categories WHERE slug='transmission_service'), 315, 455, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 5L drain+fill; NZ GST-incl'),
  ('FORD_P5AT_32_TDCI', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('FORD_YN2S_20_BITURBO', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('GWM_4N20_20_TURBO', (SELECT id FROM part_categories WHERE slug='transmission_service'), 585, 815, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'DSG/DCT fluid 6L drain+fill; NZ GST-incl'),
  ('GWM_GW4D20_20_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 315, 455, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 5L drain+fill; NZ GST-incl'),
  ('HON_B_SERIES_16_18_20', (SELECT id FROM part_categories WHERE slug='transmission_service'), 285, 405, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 3L drain+fill; NZ GST-incl'),
  ('HON_J_SERIES_V6', (SELECT id FROM part_categories WHERE slug='transmission_service'), 295, 415, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 3.5L drain+fill; NZ GST-incl'),
  ('HON_K20_20', (SELECT id FROM part_categories WHERE slug='transmission_service'), 285, 405, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 3L drain+fill; NZ GST-incl'),
  ('HON_K24_24', (SELECT id FROM part_categories WHERE slug='transmission_service'), 285, 405, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 3L drain+fill; NZ GST-incl'),
  ('HON_L13_L15_13_15', (SELECT id FROM part_categories WHERE slug='transmission_service'), 320, 460, 1, 1.5, 'moat_nz_gst_incl', 3, 'CVT fluid 3.5L drain+fill; NZ GST-incl'),
  ('HON_L15B_15T', (SELECT id FROM part_categories WHERE slug='transmission_service'), 320, 460, 1, 1.5, 'moat_nz_gst_incl', 3, 'CVT fluid 3.5L drain+fill; NZ GST-incl'),
  ('HON_LEB_15_IDCD_HYBRID', (SELECT id FROM part_categories WHERE slug='transmission_service'), 485, 640, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'DSG/DCT fluid 2.5L drain+fill; NZ GST-incl'),
  ('HON_R18A_18', (SELECT id FROM part_categories WHERE slug='transmission_service'), 285, 405, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 3L drain+fill; NZ GST-incl'),
  ('HKM_D4HA_20_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('HKM_G4FC_16', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('HKM_G4FG_G4NA_CHAIN', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('HKM_SMARTSTREAM_16_HYBRID', (SELECT id FROM part_categories WHERE slug='transmission_service'), 485, 640, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'DSG/DCT fluid 2.5L drain+fill; NZ GST-incl'),
  ('HKM_THETA_II_20_24', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('ISU_4JJ1_30_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('LDV_MAXUS_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('LR_50_SC_V8', (SELECT id FROM part_categories WHERE slug='transmission_service'), 355, 535, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 8L drain+fill; NZ GST-incl'),
  ('LR_AJ_V6_30_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 355, 535, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 8L drain+fill; NZ GST-incl'),
  ('LR_INGENIUM_20_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 355, 535, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 8L drain+fill; NZ GST-incl'),
  ('LR_INGENIUM_20_PETROL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 355, 535, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 8L drain+fill; NZ GST-incl'),
  ('MG_SAIC_15_TURBO', (SELECT id FROM part_categories WHERE slug='transmission_service'), 585, 815, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'DSG/DCT fluid 6L drain+fill; NZ GST-incl'),
  ('MAZ_13B_ROTARY', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('MAZ_B6_BP_FS_LEGACY', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('MAZ_SKYACTIVD_22', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('MAZ_SKYACTIVG_15', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('MAZ_SKYACTIVG_20', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('MAZ_SKYACTIVG_25', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('MAZ_ZY_VE_15', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('MB_M256_30_TURBO_MHEV', (SELECT id FROM part_categories WHERE slug='transmission_service'), 345, 505, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 7L drain+fill; NZ GST-incl'),
  ('MB_M271_18_FORCED', (SELECT id FROM part_categories WHERE slug='transmission_service'), 345, 505, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 7L drain+fill; NZ GST-incl'),
  ('MB_M274_20_TURBO', (SELECT id FROM part_categories WHERE slug='transmission_service'), 345, 505, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 7L drain+fill; NZ GST-incl'),
  ('MB_OM651_21_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 345, 505, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 7L drain+fill; NZ GST-incl'),
  ('MB_OM654_20_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 345, 505, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 7L drain+fill; NZ GST-incl'),
  ('MINI_B38_15_TURBO', (SELECT id FROM part_categories WHERE slug='transmission_service'), 315, 455, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 5L drain+fill; NZ GST-incl'),
  ('MINI_PRINCE_16', (SELECT id FROM part_categories WHERE slug='transmission_service'), 315, 455, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 5L drain+fill; NZ GST-incl'),
  ('MIT_4B11_4B12_20_24', (SELECT id FROM part_categories WHERE slug='transmission_service'), 395, 595, 1, 1.5, 'moat_nz_gst_incl', 3, 'CVT fluid 8L drain+fill; NZ GST-incl'),
  ('MIT_4D56_25_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('MIT_4G63_20_TURBO', (SELECT id FROM part_categories WHERE slug='transmission_service'), 237, 332, 0.8, 1.2, 'moat_nz_gst_incl', 3, '75W-90 gear oil 4L drain+fill; NZ GST-incl'),
  ('MIT_4M41_32_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('MIT_4N15_24_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('NIS_HR15DE_15', (SELECT id FROM part_categories WHERE slug='transmission_service'), 375, 565, 1, 1.5, 'moat_nz_gst_incl', 3, 'CVT fluid 7L drain+fill; NZ GST-incl'),
  ('NIS_MR18DE_18', (SELECT id FROM part_categories WHERE slug='transmission_service'), 375, 565, 1, 1.5, 'moat_nz_gst_incl', 3, 'CVT fluid 7L drain+fill; NZ GST-incl'),
  ('NIS_MR20DE_20', (SELECT id FROM part_categories WHERE slug='transmission_service'), 395, 595, 1, 1.5, 'moat_nz_gst_incl', 3, 'CVT fluid 8L drain+fill; NZ GST-incl'),
  ('NIS_QR25DE_25', (SELECT id FROM part_categories WHERE slug='transmission_service'), 395, 595, 1, 1.5, 'moat_nz_gst_incl', 3, 'CVT fluid 8L drain+fill; NZ GST-incl'),
  ('NIS_SR20_20', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('NIS_VK56_56_V8', (SELECT id FROM part_categories WHERE slug='transmission_service'), 315, 455, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 5L drain+fill; NZ GST-incl'),
  ('NIS_VQ25_VQ30_V6', (SELECT id FROM part_categories WHERE slug='transmission_service'), 315, 455, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 5L drain+fill; NZ GST-incl'),
  ('NIS_VQ35DE_35_V6', (SELECT id FROM part_categories WHERE slug='transmission_service'), 315, 455, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 5L drain+fill; NZ GST-incl'),
  ('NIS_YD25_25_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 315, 455, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 5L drain+fill; NZ GST-incl'),
  ('NIS_ZD30_30_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('SUB_EJ20_20_TURBO', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('SUB_EJ25_25_BOXER_BELT', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('SUB_EZ30_EZ36_H6', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('SUB_FB20_20_CHAIN', (SELECT id FROM part_categories WHERE slug='transmission_service'), 455, 715, 1, 1.5, 'moat_nz_gst_incl', 3, 'CVT fluid 12L drain+fill; NZ GST-incl'),
  ('SUB_FB25_25_CHAIN', (SELECT id FROM part_categories WHERE slug='transmission_service'), 455, 715, 1, 1.5, 'moat_nz_gst_incl', 3, 'CVT fluid 12L drain+fill; NZ GST-incl'),
  ('SUZ_K12B_12', (SELECT id FROM part_categories WHERE slug='transmission_service'), 360, 535, 1, 1.5, 'moat_nz_gst_incl', 3, 'CVT fluid 6L drain+fill; NZ GST-incl'),
  ('SUZ_K14_14', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('SUZ_K6A_F6A_KEI', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('SUZ_M16A_16', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('TOY_1AZFE_20', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('TOY_1GDFTV_28_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('TOY_1GRFE_40_V6', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('TOY_1HZ_42_DIESEL_I6', (SELECT id FROM part_categories WHERE slug='transmission_service'), 242, 347, 0.8, 1.2, 'moat_nz_gst_incl', 3, '75W-90 gear oil 4.5L drain+fill; NZ GST-incl'),
  ('TOY_1JZ_25_I6', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('TOY_1KDFTV_30_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('TOY_1KRFE_10', (SELECT id FROM part_categories WHERE slug='transmission_service'), 370, 550, 1, 1.5, 'moat_nz_gst_incl', 3, 'CVT fluid 6.5L drain+fill; NZ GST-incl'),
  ('TOY_1KZTE_30_TDIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('TOY_1MZFE_30_V6', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('TOY_1NR_2NR_13_15', (SELECT id FROM part_categories WHERE slug='transmission_service'), 370, 550, 1, 1.5, 'moat_nz_gst_incl', 3, 'CVT fluid 6.5L drain+fill; NZ GST-incl'),
  ('TOY_1NZFE_15', (SELECT id FROM part_categories WHERE slug='transmission_service'), 275, 375, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 2L drain+fill; NZ GST-incl'),
  ('TOY_1ZRFE_16', (SELECT id FROM part_categories WHERE slug='transmission_service'), 370, 550, 1, 1.5, 'moat_nz_gst_incl', 3, 'CVT fluid 6.5L drain+fill; NZ GST-incl'),
  ('TOY_2ARFE_25', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('TOY_2AZFE_24', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('TOY_2GDFTV_24_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('TOY_2GRFE_35_V6', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('TOY_2JZ_30_I6', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('TOY_2KDFTV_25_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('TOY_2NZFE_13', (SELECT id FROM part_categories WHERE slug='transmission_service'), 275, 375, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 2L drain+fill; NZ GST-incl'),
  ('TOY_2ZRFE_18', (SELECT id FROM part_categories WHERE slug='transmission_service'), 370, 550, 1, 1.5, 'moat_nz_gst_incl', 3, 'CVT fluid 6.5L drain+fill; NZ GST-incl'),
  ('TOY_3MZFE_33_V6', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('TOY_4AFE_7AFE_16_18', (SELECT id FROM part_categories WHERE slug='transmission_service'), 275, 375, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 2L drain+fill; NZ GST-incl'),
  ('TOY_5LE_30_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('TOY_5VZFE_34_V6', (SELECT id FROM part_categories WHERE slug='transmission_service'), 300, 430, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 4L drain+fill; NZ GST-incl'),
  ('VW_EA111_14_TSI', (SELECT id FROM part_categories WHERE slug='transmission_service'), 610, 865, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'DSG/DCT fluid 7L drain+fill; NZ GST-incl'),
  ('VW_EA113_20_TFSI', (SELECT id FROM part_categories WHERE slug='transmission_service'), 610, 865, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'DSG/DCT fluid 7L drain+fill; NZ GST-incl'),
  ('VW_EA189_20_TDI', (SELECT id FROM part_categories WHERE slug='transmission_service'), 610, 865, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'DSG/DCT fluid 7L drain+fill; NZ GST-incl'),
  ('VW_EA211_10_TSI_3CYL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 610, 865, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'DSG/DCT fluid 7L drain+fill; NZ GST-incl'),
  ('VW_EA211_14_TSI', (SELECT id FROM part_categories WHERE slug='transmission_service'), 610, 865, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'DSG/DCT fluid 7L drain+fill; NZ GST-incl'),
  ('VW_EA211_GTE_PHEV', (SELECT id FROM part_categories WHERE slug='transmission_service'), 640, 915, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'DSG/DCT fluid 8L drain+fill; NZ GST-incl'),
  ('VW_EA888_20_TSI', (SELECT id FROM part_categories WHERE slug='transmission_service'), 610, 865, 1.5, 2.5, 'moat_nz_gst_incl', 3, 'DSG/DCT fluid 7L drain+fill; NZ GST-incl'),
  ('VOLVO_VEA_20_DIESEL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 330, 480, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 6L drain+fill; NZ GST-incl'),
  ('VOLVO_VEA_20_PETROL', (SELECT id FROM part_categories WHERE slug='transmission_service'), 330, 480, 1, 1.5, 'moat_nz_gst_incl', 3, 'ATF Dexron VI 6L drain+fill; NZ GST-incl')
) AS v(engine_family_id, category_id, total_job_low, total_job_high, hours_low, hours_high, source_anchor, confidence, notes)
ON CONFLICT (engine_family_id, category_id) DO NOTHING;
